name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:

    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.7
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.3.0
        run_install: true

    - name: Lint
      run: pnpm run lint

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    needs: lint
    env:
      NODE_VERSION: 14
      GIT_COMMITTER_NAME: cherryblossom
      GIT_COMMITTER_EMAIL: 31467609+cherryblossom000@users.noreply.github.com

    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.7
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.3.0
        run_install: true

    - name: Release
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
