name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:

    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node }}

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.3.0
        run_install: true

    - name: Lint
      run: pnpm run lint

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    needs: build
    steps:

    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '14'

    - uses: crazy-max/ghaction-import-gpg@v3.1.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.3.0
        run_install: true

    - name: Release
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
