name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '12'
    - name: Install
      run: npm i -g pnpm && pnpm i
    - name: Lint
      run: pnpm run lint

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    needs: build
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '12'
    - uses: crazy-max/ghaction-import-gpg@v3.1.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true
    - name: Install
      run: npm i -g pnpm && pnpm i
    - name: Release
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
